name: ack
description: A simple validation library for Dart
version: 1.0.0-beta.3
repository: https://github.com/btwld/ack
issue_tracker: https://github.com/btwld/ack/issues
homepage: https://docs.page/btwld/ack


environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  meta: ^1.15.0
  collection: ^1.18.0

dev_dependencies:
  coverage: ^1.11.1
  dart_code_metrics_presets: ^2.22.0
  lints: ^5.0.0
  path: ^1.9.0
  test: ^1.24.0
