name: ack_example
description: Example project for ACK schema generation.
version: 1.0.0-beta.1
publish_to: none

resolution: workspace

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  ack: ^1.0.0-beta.4

dev_dependencies:
  ack_generator: ^1.0.0-beta.1
  build_runner: ^2.4.0
  dart_code_metrics_presets: ^2.22.0
  lints: ^5.0.0


# Override dependencies to use local packages
# dependency_overrides:
#   ack:
#     path: ../packages/ack
#   ack_generator:
#     path: ../packages/ack_generator
