name: ack_annotations
description: Annotations for Ack schema code generation
version: 1.0.0-beta.7
repository: https://github.com/btwld/ack
resolution: workspace

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  meta: ^1.15.0

dev_dependencies:
