name: ack_json_schema_builder
description: JSON Schema Builder converter for ACK validation library
version: 1.0.0-beta.4
repository: https://github.com/btwld/ack
issue_tracker: https://github.com/btwld/ack/issues

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  ack: ^1.0.0-beta.4
  json_schema_builder: ^0.1.3
  meta: ^1.15.0

dev_dependencies:
  test: ^1.24.0
  lints: ^5.0.0
